apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: drones.core.kube-hive.org
spec:
  group: core.kube-hive.org
  names:
    kind: Drone
    listKind: DroneList
    plural: drones
    singular: drone
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Drone is the Schema for the drones API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DroneSpec defines the desired state of Drone
          type: object
        status:
          description: DroneStatus defines the observed state of Drone
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
